import type { Metadata } from "next";
import { Inter, Orbitron, Bebas_Neue } from "next/font/google"; // Assuming you are using next/font
import "./globals.css"; // <--- CRITICAL: This imports Tailwind

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const orbitron = Orbitron({ subsets: ["latin"], variable: "--font-orbitron" });
const bebas = Bebas_Neue({ weight: "400", subsets: ["latin"], variable: "--font-bebas" });

export const metadata: Metadata = {
  title: "Next.js Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${orbitron.variable} ${bebas.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}